#!/usr/bin/with-contenv bash

if [ ! -f /config/dictionary.json ]; then
  echo "**** Setting up ServerPackCreator configuration. ****"
  cp -f \
    /defaults/dictionary.json \
    /config/dictionary.json
fi

ln -sf /config/dictionary.json /app/chatbot/data/dictionary.json

chown -R \
  grfd:grfd \
    /app/chatbot \
    /config